useDotenv: true
service: commit-genie
frameworkVersion: '3'
	
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  profile: personalAccount

functions:
  commitgenie:
    handler: index.handler
    events:
      - schedule: cron(0 12 ? * 1-7 *)

